name: Lint
on: [push, pull_request]

jobs:
  php_cs_fixer:
    name: PHP-CS-Fxier
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version:
          - 7.2
        perfer:
          - stable
    container:
      image: nauxliu/php-ci-image:${{ matrix.php_version }}
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer install --no-progress
    - name: Run PHP-CS-Fxier
      run: ./vendor/bin/php-cs-fixer fix --dry-run --diff 1>&2
